## Importing Libraries

In [1]:
import json
import pandas as pd
import ijson

### Extract each item

In [2]:
filename = "C:/Users/vpare/OneDrive/Desktop/data project/API.json"
with open(filename, 'r',encoding='utf-8') as f:
    #Extract each item from the meta.view.columns list
    objects = ijson.items(f, 'meta.view.columns.item') 
    columns = list(objects) #Convert generator to list

In [3]:
columns

[{'id': -1,
  'name': 'sid',
  'dataTypeName': 'meta_data',
  'fieldName': ':sid',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'id',
  'dataTypeName': 'meta_data',
  'fieldName': ':id',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'position',
  'dataTypeName': 'meta_data',
  'fieldName': ':position',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'created_at',
  'dataTypeName': 'meta_data',
  'fieldName': ':created_at',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'created_meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':created_meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'updated_at',
  'dataTypeName': 'meta_data',
  'fieldName': ':updated_at',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'updated_meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':updated_meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': 45985351,
  'name': 'DBN',
  'dataTypeName': 'text',
  'fieldName': 'dbn',
  'position': 1,
  'renderTypeName': 'text',
  'tableColumnId': 8032537,
  'cachedContents': {'non_null': 10075,
   'largest': '32K564',
   'null': 0,
   'top': [{'item': '31R460', 'count': 20},
    {'item': '31R470', 'count': 19},
    {'item': '31R600', 'count': 18},
    {'item': '31R605', 'count': 17},
    {'item': '32K045', 'count': 16},
    {'item': '32K075', 'count': 15},
    {'item': '32K086', 'count': 14},
    {'item': '32K106', 'count': 13},
    {'item': '32K116', 'count': 12},
    {'item': '32K123', 'count': 11},
    {'item': '32K145', 'count': 10},
    {'item': '32K151', 'count': 9},
    {'item': '32K162', 'count': 8},
    {'item': '32K274', 'count': 7},
    {'item': '32K291', 'count': 6},
    {'item': '32K296', 'count': 5},
    {'item': '32K299', 'count': 4},
    {'item': '32K347', 'count': 3},
    {'item': '32K349', 'count': 2},
    {'item': '32K376', 'count': 1}],
   'smallest': '01M015'},
  'format': {}},
 {'id': 45985352,
  'name': 'Name',
  'dataTypeName': 'text',
  'fieldName': 'name',
  'position': 2,
  'renderTypeName': 'text',
  'tableColumnId': 8032538,
  'cachedContents': {'non_null': 10075,
   'largest': "YOUNG WOMEN'S LEADERSHIP SCHOOL QUEENS          ",
   'null': 0,
   'top': [{'item': 'PORT RICHMOND HIGH SCHOOL', 'count': 20},
    {'item': 'CURTIS HIGH SCHOOL', 'count': 19},
    {'item': 'TOTTENVILLE HIGH SCHOOL', 'count': 18},
    {'item': 'SUSAN E. WAGNER HIGH SCHOOL', 'count': 17},
    {'item': 'CONCORD HIGH SCHOOL', 'count': 16},
    {'item': 'RALPH R. MCKEE CAREER AND TECHNICAL HIGH SCHOOL', 'count': 15},
    {'item': 'STATEN ISLAND TECHNICAL HIGH SCHOOL', 'count': 14},
    {'item': 'PS 045 HORACE E GREENE', 'count': 13},
    {'item': 'PS 075 MAYDA CORTIELLA', 'count': 12},
    {'item': 'PS 086 THE IRVINGTON', 'count': 11},
    {'item': 'PS 106 EDWARD EVERETT HALE', 'count': 10},
    {'item': 'PS 116 ELIZABETH L FARRELL', 'count': 9},
    {'item': 'PS 123 SUYDAM', 'count': 8},
    {'item': 'PS 145 ANDREW JACKSON', 'count': 7},
    {'item': 'PS 151 LYNDON B JOHNSON', 'count': 6},
    {'item': 'JHS 162 THE WILLOUGHBY', 'count': 5},
    {'item': 'PS 274 KOSCIUSKO', 'count': 4},
    {'item': 'JHS 291 ROLAND HAYES', 'count': 3},
    {'item': 'JHS 296 THE HALSEY', 'count': 2},
    {'item': 'PS 299 THOMAS WARREN FIELD', 'count': 1}],
   'smallest': '47 THE AMERICAN SIGN LANGUAGE AND ENGLISH DUAL L'},
  'format': {}},
 {'id': 45985353,
  'name': 'schoolyear',
  'dataTypeName': 'text',
  'fieldName': 'schoolyear',
  'position': 3,
  'renderTypeName': 'text',
  'tableColumnId': 8032539,
  'cachedContents': {'non_null': 10075,
   'largest': '20112012',
   'null': 0,
   'top': [{'item': '20052006', 'count': 20},
    {'item': '20062007', 'count': 19},
    {'item': '20072008', 'count': 18},
    {'item': '20082009', 'count': 17},
    {'item': '20092010', 'count': 16},
    {'item': '20102011', 'count': 15},
    {'item': '20112012', 'count': 14}],
   'smallest': '20052006'},
  'format': {}},
 {'id': 45985354,
  'name': 'fl_percent',
  'dataTypeName': 'text',
  'fieldName': 'fl_percent',
  'position': 4,
  'renderTypeName': 'text',
  'tableColumnId': 8032540,
  'cachedContents': {'non_null': 8566,
   'largest': 'n/a',
   'null': 1509,
   'top': [{'item': '   ', 'count': 20},
    {'item': '82.6', 'count': 19},
    {'item': '41.2', 'count': 18},
    {'item': '92', 'count': 17},
    {'item': '86.5', 'count': 16},
    {'item': '93.7', 'count': 15},
    {'item': '97.6', 'count': 14},
    {'item': '78.4', 'count': 13},
    {'item': '89', 'count': 12},
    {'item': '89.4', 'count': 11},
    {'item': '75', 'count': 10},
    {'item': '84.2', 'count': 9},
    {'item': '86.3', 'count': 8},
    {'item': '97.2', 'count': 7},
    {'item': '62.1', 'count': 6},
    {'item': '77.6', 'count': 5},
    {'item': '66.9', 'count': 4},
    {'item': '89.2', 'count': 3},
    {'item': '93.2', 'count': 2},
    {'item': '96.1', 'count': 1}],
   'smallest': '   '},
  'format': {}},
 {'id': 45985355,
  'name': 'frl_percent',
  'dataTypeName': 'text',
  'fieldName': 'frl_percent',
  'position': 5,
  'renderTypeName': 'text',
  'tableColumnId': 8032541,
  'cachedContents': {'non_null': 4482,
   'largest': '99.9',
   'null': 5593,
   'top': [{'item': '86.4', 'count': 20},
    {'item': '96.8', 'count': 19},
    {'item': '95.5', 'count': 18},
    {'item': '94.9', 'count': 17},
    {'item': '82', 'count': 16},
    {'item': '87.6', 'count': 15},
    {'item': '66.2', 'count': 14},
    {'item': '88.8', 'count': 13},
    {'item': '88', 'count': 12},
    {'item': '89.2', 'count': 11},
    {'item': '88.2', 'count': 10},
    {'item': '81.8', 'count': 9}],
   'smallest': '10'},
  'format': {}},
 {'id': 45985356,
  'name': 'total_enrollment',
  'dataTypeName': 'text',
  'fieldName': 'total_enrollment',
  'position': 6,
  'renderTypeName': 'text',
  'tableColumnId': 8032542,
  'cachedContents': {'non_null': 10075,
   'largest': '999',
   'null': 0,
   'top': [{'item': '420', 'count': 20},
    {'item': '434', 'count': 19},
    {'item': '363', 'count': 18},
    {'item': '458', 'count': 17},
    {'item': '484', 'count': 16},
    {'item': '461', 'count': 15},
    {'item': '469', 'count': 14},
    {'item': '471', 'count': 13},
    {'item': '398', 'count': 12},
    {'item': '237', 'count': 11},
    {'item': '255', 'count': 10},
    {'item': '266', 'count': 9},
    {'item': '257', 'count': 8},
    {'item': '251', 'count': 7},
    {'item': '238', 'count': 6},
    {'item': '263', 'count': 5},
    {'item': '300', 'count': 4},
    {'item': '417', 'count': 3},
    {'item': '489', 'count': 2},
    {'item': '481', 'count': 1}],
   'smallest': '1'},
  'format': {}},
 {'id': 45985357,
  'name': 'prek',
  'dataTypeName': 'text',
  'fieldName': 'prek',
  'position': 7,
  'renderTypeName': 'text',
  'tableColumnId': 8032543,
  'cachedContents': {'non_null': 4712,
   'largest': '99',
   'null': 5363,
   'top': [{'item': '18', 'count': 20},
    {'item': '17', 'count': 19},
    {'item': '16', 'count': 18},
    {'item': '33', 'count': 17},
    {'item': '35', 'count': 16},
    {'item': '36', 'count': 15},
    {'item': '32', 'count': 14},
    {'item': '34', 'count': 13},
    {'item': '52', 'count': 12},
    {'item': '54', 'count': 11},
    {'item': '31', 'count': 10},
    {'item': '29', 'count': 9},
    {'item': '    ', 'count': 8},
    {'item': '30', 'count': 7},
    {'item': '53', 'count': 6},
    {'item': '72', 'count': 5},
    {'item': '71', 'count': 4},
    {'item': '28', 'count': 3},
    {'item': '70', 'count': 2},
    {'item': '27', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985358,
  'name': 'k',
  'dataTypeName': 'text',
  'fieldName': 'k',
  'position': 8,
  'renderTypeName': 'text',
  'tableColumnId': 8032544,
  'cachedContents': {'non_null': 5882,
   'largest': '99',
   'null': 4193,
   'top': [{'item': '    ', 'count': 20},
    {'item': '96', 'count': 19},
    {'item': '101', 'count': 18},
    {'item': '114', 'count': 17},
    {'item': '75', 'count': 16},
    {'item': '76', 'count': 15},
    {'item': '94', 'count': 14},
    {'item': '81', 'count': 13},
    {'item': '77', 'count': 12},
    {'item': '88', 'count': 11},
    {'item': '104', 'count': 10},
    {'item': '154', 'count': 9},
    {'item': '68', 'count': 8},
    {'item': '62', 'count': 7},
    {'item': '97', 'count': 6},
    {'item': '59', 'count': 5},
    {'item': '64', 'count': 4},
    {'item': '69', 'count': 3},
    {'item': '57', 'count': 2},
    {'item': '87', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985359,
  'name': 'grade1',
  'dataTypeName': 'text',
  'fieldName': 'grade1',
  'position': 9,
  'renderTypeName': 'text',
  'tableColumnId': 8032545,
  'cachedContents': {'non_null': 5881,
   'largest': '99',
   'null': 4194,
   'top': [{'item': '    ', 'count': 20},
    {'item': '120', 'count': 19},
    {'item': '74', 'count': 18},
    {'item': '100', 'count': 17},
    {'item': '94', 'count': 16},
    {'item': '88', 'count': 15},
    {'item': '78', 'count': 14},
    {'item': '75', 'count': 13},
    {'item': '66', 'count': 12},
    {'item': '67', 'count': 11},
    {'item': '83', 'count': 10},
    {'item': '141', 'count': 9},
    {'item': '147', 'count': 8},
    {'item': '124', 'count': 7},
    {'item': '114', 'count': 6},
    {'item': '111', 'count': 5},
    {'item': '103', 'count': 4},
    {'item': '105', 'count': 3},
    {'item': '96', 'count': 2},
    {'item': '68', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985360,
  'name': 'grade2',
  'dataTypeName': 'text',
  'fieldName': 'grade2',
  'position': 10,
  'renderTypeName': 'text',
  'tableColumnId': 8032546,
  'cachedContents': {'non_null': 5851,
   'largest': '99',
   'null': 4224,
   'top': [{'item': '    ', 'count': 20},
    {'item': '115', 'count': 19},
    {'item': '138', 'count': 18},
    {'item': '84', 'count': 17},
    {'item': '85', 'count': 16},
    {'item': '92', 'count': 15},
    {'item': '144', 'count': 14},
    {'item': '86', 'count': 13},
    {'item': '64', 'count': 12},
    {'item': '68', 'count': 11},
    {'item': '61', 'count': 10},
    {'item': '147', 'count': 9},
    {'item': '139', 'count': 8},
    {'item': '136', 'count': 7},
    {'item': '117', 'count': 6},
    {'item': '110', 'count': 5},
    {'item': '94', 'count': 4},
    {'item': '89', 'count': 3},
    {'item': '80', 'count': 2},
    {'item': '78', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985361,
  'name': 'grade3',
  'dataTypeName': 'text',
  'fieldName': 'grade3',
  'position': 11,
  'renderTypeName': 'text',
  'tableColumnId': 8032547,
  'cachedContents': {'non_null': 5779,
   'largest': '99',
   'null': 4296,
   'top': [{'item': '    ', 'count': 20},
    {'item': '107', 'count': 19},
    {'item': '136', 'count': 18},
    {'item': '143', 'count': 17},
    {'item': '84', 'count': 16},
    {'item': '83', 'count': 15},
    {'item': '79', 'count': 14},
    {'item': '129', 'count': 13},
    {'item': '85', 'count': 12},
    {'item': '93', 'count': 11},
    {'item': '77', 'count': 10},
    {'item': '87', 'count': 9},
    {'item': '73', 'count': 8},
    {'item': '65', 'count': 7},
    {'item': '78', 'count': 6},
    {'item': '103', 'count': 5},
    {'item': '99', 'count': 4},
    {'item': '102', 'count': 3},
    {'item': '101', 'count': 2},
    {'item': '94', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985362,
  'name': 'grade4',
  'dataTypeName': 'text',
  'fieldName': 'grade4',
  'position': 12,
  'renderTypeName': 'text',
  'tableColumnId': 8032548,
  'cachedContents': {'non_null': 5741,
   'largest': '99',
   'null': 4334,
   'top': [{'item': '    ', 'count': 20},
    {'item': '96', 'count': 19},
    {'item': '118', 'count': 18},
    {'item': '128', 'count': 17},
    {'item': '82', 'count': 16},
    {'item': '102', 'count': 15},
    {'item': '91', 'count': 14},
    {'item': '84', 'count': 13},
    {'item': '92', 'count': 12},
    {'item': '134', 'count': 11},
    {'item': '141', 'count': 10},
    {'item': '136', 'count': 9},
    {'item': '95', 'count': 8},
    {'item': '90', 'count': 7},
    {'item': '74', 'count': 6},
    {'item': '80', 'count': 5},
    {'item': '89', 'count': 4},
    {'item': '70', 'count': 3}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985363,
  'name': 'grade5',
  'dataTypeName': 'text',
  'fieldName': 'grade5',
  'position': 13,
  'renderTypeName': 'text',
  'tableColumnId': 8032549,
  'cachedContents': {'non_null': 5777,
   'largest': '99',
   'null': 4298,
   'top': [{'item': '    ', 'count': 20},
    {'item': '97', 'count': 19},
    {'item': '85', 'count': 18},
    {'item': '108', 'count': 17},
    {'item': '119', 'count': 16},
    {'item': '71', 'count': 15},
    {'item': '55', 'count': 14},
    {'item': '122', 'count': 13},
    {'item': '84', 'count': 12},
    {'item': '82', 'count': 11},
    {'item': '90', 'count': 10},
    {'item': '130', 'count': 9},
    {'item': '101', 'count': 8},
    {'item': '75', 'count': 7},
    {'item': '91', 'count': 6},
    {'item': '100', 'count': 5},
    {'item': '77', 'count': 4},
    {'item': '74', 'count': 3},
    {'item': '80', 'count': 2},
    {'item': '70', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985364,
  'name': 'grade6',
  'dataTypeName': 'text',
  'fieldName': 'grade6',
  'position': 14,
  'renderTypeName': 'text',
  'tableColumnId': 8032550,
  'cachedContents': {'non_null': 4517,
   'largest': '99',
   'null': 5558,
   'top': [{'item': '    ', 'count': 20},
    {'item': '98', 'count': 19},
    {'item': '99', 'count': 18},
    {'item': '176', 'count': 17},
    {'item': '159', 'count': 16},
    {'item': '183', 'count': 15},
    {'item': '83', 'count': 14},
    {'item': '90', 'count': 13},
    {'item': '97', 'count': 12},
    {'item': '117', 'count': 11},
    {'item': '93', 'count': 10},
    {'item': '75', 'count': 9},
    {'item': '326', 'count': 8},
    {'item': '386', 'count': 7},
    {'item': '405', 'count': 6},
    {'item': '372', 'count': 5},
    {'item': '268', 'count': 4},
    {'item': '274', 'count': 3},
    {'item': '59', 'count': 2},
    {'item': '87', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985365,
  'name': 'grade7',
  'dataTypeName': 'text',
  'fieldName': 'grade7',
  'position': 15,
  'renderTypeName': 'text',
  'tableColumnId': 8032551,
  'cachedContents': {'non_null': 4203,
   'largest': '99',
   'null': 5872,
   'top': [{'item': '    ', 'count': 20},
    {'item': '162', 'count': 19},
    {'item': '75', 'count': 18},
    {'item': '332', 'count': 17},
    {'item': '373', 'count': 16},
    {'item': '397', 'count': 15},
    {'item': '359', 'count': 14},
    {'item': '258', 'count': 13},
    {'item': '251', 'count': 12},
    {'item': '53', 'count': 11},
    {'item': '70', 'count': 10},
    {'item': '60', 'count': 9},
    {'item': '66', 'count': 8},
    {'item': '67', 'count': 7},
    {'item': '29', 'count': 6},
    {'item': '33', 'count': 5},
    {'item': '26', 'count': 4},
    {'item': '28', 'count': 3},
    {'item': '30', 'count': 2},
    {'item': '32', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985366,
  'name': 'grade8',
  'dataTypeName': 'text',
  'fieldName': 'grade8',
  'position': 16,
  'renderTypeName': 'text',
  'tableColumnId': 8032552,
  'cachedContents': {'non_null': 4085,
   'largest': '99',
   'null': 5990,
   'top': [{'item': '    ', 'count': 20},
    {'item': '335', 'count': 19},
    {'item': '367', 'count': 18},
    {'item': '181', 'count': 17},
    {'item': '193', 'count': 16},
    {'item': '68', 'count': 15},
    {'item': '59', 'count': 14},
    {'item': '60', 'count': 13},
    {'item': '58', 'count': 12},
    {'item': '31', 'count': 11},
    {'item': '48', 'count': 10},
    {'item': '37', 'count': 9},
    {'item': '30', 'count': 8}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985367,
  'name': 'grade9',
  'dataTypeName': 'text',
  'fieldName': 'grade9',
  'position': 17,
  'renderTypeName': 'text',
  'tableColumnId': 8032553,
  'cachedContents': {'non_null': 3974,
   'largest': '999',
   'null': 6101,
   'top': [{'item': '    ', 'count': 20},
    {'item': '135', 'count': 19},
    {'item': '121', 'count': 18},
    {'item': '1', 'count': 17},
    {'item': '231', 'count': 16},
    {'item': '99', 'count': 15},
    {'item': '96', 'count': 14},
    {'item': '66', 'count': 13},
    {'item': '155', 'count': 12},
    {'item': '177', 'count': 11},
    {'item': '174', 'count': 10},
    {'item': '171', 'count': 9},
    {'item': '127', 'count': 8},
    {'item': '131', 'count': 7},
    {'item': '134', 'count': 6},
    {'item': '142', 'count': 5},
    {'item': '140', 'count': 4},
    {'item': '145', 'count': 3},
    {'item': '124', 'count': 2},
    {'item': '118', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985368,
  'name': 'grade10',
  'dataTypeName': 'text',
  'fieldName': 'grade10',
  'position': 18,
  'renderTypeName': 'text',
  'tableColumnId': 8032554,
  'cachedContents': {'non_null': 3846,
   'largest': '998',
   'null': 6229,
   'top': [{'item': '    ', 'count': 20},
    {'item': '94', 'count': 19},
    {'item': '220', 'count': 18},
    {'item': '229', 'count': 17},
    {'item': '105', 'count': 16},
    {'item': '122', 'count': 15},
    {'item': '138', 'count': 14},
    {'item': '130', 'count': 13},
    {'item': '143', 'count': 12},
    {'item': '141', 'count': 11},
    {'item': '104', 'count': 10},
    {'item': '23', 'count': 9},
    {'item': '46', 'count': 8},
    {'item': '49', 'count': 7},
    {'item': '50', 'count': 6},
    {'item': '37', 'count': 5},
    {'item': '34', 'count': 4},
    {'item': '117', 'count': 3},
    {'item': '99', 'count': 2},
    {'item': '121', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985369,
  'name': 'grade11',
  'dataTypeName': 'text',
  'fieldName': 'grade11',
  'position': 19,
  'renderTypeName': 'text',
  'tableColumnId': 8032555,
  'cachedContents': {'non_null': 3674,
   'largest': '992',
   'null': 6401,
   'top': [{'item': '    ', 'count': 20},
    {'item': '226', 'count': 19},
    {'item': '73', 'count': 18},
    {'item': '78', 'count': 17},
    {'item': '1', 'count': 16},
    {'item': '158', 'count': 15},
    {'item': '134', 'count': 14},
    {'item': '117', 'count': 13},
    {'item': '162', 'count': 12},
    {'item': '175', 'count': 11},
    {'item': '180', 'count': 10},
    {'item': '155', 'count': 9},
    {'item': '99', 'count': 8},
    {'item': '100', 'count': 7},
    {'item': '83', 'count': 6},
    {'item': '79', 'count': 5},
    {'item': '93', 'count': 4},
    {'item': '107', 'count': 3},
    {'item': '91', 'count': 2},
    {'item': '81', 'count': 1}],
   'smallest': '    '},
  'format': {}},
 {'id': 45985370,
  'name': 'grade12',
  'dataTypeName': 'text',
  'fieldName': 'grade12',
  'position': 20,
  'renderTypeName': 'text',
  'tableColumnId': 8032556,
  'cachedContents': {'non_null': 3513,
   'largest': '994',
   'null': 6562,
   'top': [{'item': '    ', 'count': 20},
    {'item': '152', 'count': 19},
    {'item': '128', 'count': 18},
    {'item': '78', 'count': 17},
    {'item': '69', 'count': 16},
    {'item': '98', 'count': 15},
    {'item': '81', 'count': 14},
    {'item': '90', 'count': 13},
    {'item': '25', 'count': 12},
    {'item': '21', 'count': 11},
    {'item': '43', 'count': 10},
    {'item': '49', 'count': 9},
    {'item': '39', 'count': 8},
    {'item': '35', 'count': 7},
    {'item': '87', 'count': 6},
    {'item': '89', 'count': 5},

In [4]:
column_names = [col["fieldName"] for col in columns]
column_names

[':sid',
 ':id',
 ':position',
 ':created_at',
 ':created_meta',
 ':updated_at',
 ':updated_meta',
 ':meta',
 'dbn',
 'name',
 'schoolyear',
 'fl_percent',
 'frl_percent',
 'total_enrollment',
 'prek',
 'k',
 'grade1',
 'grade2',
 'grade3',
 'grade4',
 'grade5',
 'grade6',
 'grade7',
 'grade8',
 'grade9',
 'grade10',
 'grade11',
 'grade12',
 'ell_num',
 'ell_percent',
 'sped_num',
 'sped_percent',
 'ctt_num',
 'selfcontained_num',
 'asian_num',
 'asian_per',
 'black_num',
 'black_per',
 'hispanic_num',
 'hispanic_per',
 'white_num',
 'white_per',
 'male_num',
 'male_per',
 'female_num',
 'female_per']

In [5]:
main_columns=['dbn',
 'name',
 'schoolyear',
 'fl_percent',
 'frl_percent',
 'total_enrollment',
 'prek',
 'k',
 'grade1',
 'grade2',
 'grade3',
 'grade4',
 'grade5',
 'grade6',
 'grade7',
 'grade8',
 'grade9',
 'grade10',
 'grade11',
 'grade12',
 'ell_num',
 'ell_percent',
 'sped_num',
 'sped_percent',
 'ctt_num',
 'selfcontained_num',
 'asian_num',
 'asian_per',
 'black_num',
 'black_per',
 'hispanic_num',
 'hispanic_per',
 'white_num',
 'white_per',
 'male_num',
 'male_per',
 'female_num',
 'female_per']

## Extract data

In [6]:
data = []

with open(filename, 'r',encoding='utf-8') as f:
    objects = ijson.items(f, 'data.item')
    for row in objects:
        selected_row = []
        for item in main_columns:
            selected_row.append(row[column_names.index(item)])
        data.append(selected_row)

In [7]:
data = pd.DataFrame(data, columns=main_columns)
data

,dbn,name,schoolyear,fl_percent,frl_percent,total_enrollment,prek,k,grade1,grade2,...,black_num,black_per,hispanic_num,hispanic_per,white_num,white_per,male_num,male_per,female_num,female_per
0,01M015,P.S. 015 ROBERTO CLEMENTE,20052006,89.4,None,281,15,36,40,33,...,74,26.3,189,67.3,5,1.8,158,56.2,123,43.8
1,01M015,P.S. 015 ROBERTO CLEMENTE,20062007,89.4,None,243,15,29,39,38,...,68,28,153,63,4,1.6,140,57.6,103,42.4
2,01M015,P.S. 015 ROBERTO CLEMENTE,20072008,89.4,None,261,18,43,39,36,...,77,29.5,157,60.2,7,2.7,143,54.8,118,45.2
3,01M015,P.S. 015 ROBERTO CLEMENTE,20082009,89.4,None,252,17,37,44,32,...,75,29.8,149,59.1,7,2.8,149,59.1,103,40.9
4,01M015,P.S. 015 ROBERTO CLEMENTE,20092010,,96.5,208,16,40,28,32,...,67,32.2,118,56.7,6,2.9,124,59.6,84,40.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10070,32K564,BUSHWICK COMMUNITY HIGH SCHOOL,20072008,85.6,None,355,None,None,None,None,...,151,42.5,198,55.8,5,1.4,181,51,174,49
10071,32K564,BUSHWICK COMMUNITY HIGH SCHOOL,20082009,65.2,None,383,None,None,None,None,...,132,34.5,245,64,2,0.5,206,53.8,177,46.2
10072,32K564,BUSHWICK COMMUNITY HIGH SCHOOL,20092010,,89.2,395,None,None,None,None,...,146,37,242,61.3,3,0.8,199,50.4,196,49.6
10073,32K564,BUSHWICK COMMUNITY HIGH SCHOOL,20102011,,88.2,420,None,None,None,None,...,166,39.5,242,57.6,8,1.9,209,49.8,211,50.2
10074,32K564,BUSHWICK COMMUNITY HIGH SCHOOL,20112012,None,81.8,382,,,,,...,137,35.9,235,61.5,7,1.8,169,44.2,213,55.8

In [8]:
data.to_csv("C:/Users/vpare/OneDrive/Desktop/data project/NY.csv")